image: 
  gitpod/workspace-dotnet

tasks:
  - name: resolve paket dependencies
    init: |
      dotnet tool restore
      dotnet paket restore
      dotnet paket generate-load-scripts --type fsx

vscode:
  extensions:
    - ionide.ionide-fsharp
    - oderwat.indent-rainbow
    - esbenp.prettier-vscode
    - ms-azuretools.vscode-docker
    - vscode-icons-team.vscode-icons
    - muhammad-sammy.csharp