github:
  prebuilds:
    master: true
    branches: true
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: true

image: 
  gitpod/workspace-dotnet

tasks:
  - name: paket availability 
    init: |
      dotnet tool restore
  - name: manage dependencies
    command: |
      dotnet paket restore
      dotnet paket generate-load-scripts --type fsx

vscode:
  extensions:
    - muhammad-sammy.csharp
    - ionide.ionide-fsharp
    - oderwat.indent-rainbow
    - esbenp.prettier-vscode
    - ms-azuretools.vscode-docker
    - vscode-icons-team.vscode-icons