image: 
  gitpod/workspace-dotnet
vscode:
  extensions:
    - ionide.ionide-fsharp
    - oderwat.indent-rainbow
    - esbenp.prettier-vscode
    - ms-azuretools.vscode-docker
    - vscode-icons-team.vscode-icons
    - muhammad-sammy.csharp
